---
- name: Run gitlab service
  command: >
    docker service create \
      --name gitlab \
      --replicas=1 \
      --network my-net \
      --label traefik.port=80 \
      --label traefik.frontend.rule=Host:gitlab.localhost \
      --constraint 'node.role == manager' \
      --mount type=bind,src=//srv/gitlab/config,dst=/etc/gitlab \
      --mount type=bind,src=/srv/gitlab/logs,dst=/var/log/gitlab \
      --mount type=bind,src=//srv/gitlab/data,dst=/var/opt/gitlab \
      gitlab/gitlab-ce:latest