---
- name: Run gitlab-runners service
  command: >
    docker service create \
      --name "{{ item }}" \
      --replicas=1 \
      --network my-net \
      --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
      --mount type=bind,src=/srv/gitlab-runner/config,dst=/etc/gitlab-runner \
      gitlab/gitlab-runner
  with_items: 
    - gitlab-runner-1
    - gitlab-runner-2
    - gitlab-runner-3


