---
- name: Run visualizer service
  command: >
    docker service create \
      --name gr \
      --replicas=1 \
      --network my-net \
      --secret gitlab-runner-token
      --constraint 'node.role == manager'
      --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
      gitlab/gitlab-runner \
      register \
      -n \
      -u "http://gitlab" \
      -r twrGiAYusokXHsuNqsQN \
      --executor docker \
      --docker-image docker:latest \
      --docker-network-mode my-net \
      --docker-volumes "/var/run/docker.sock:/var/run/docker.sock" 